sudo: required
services:
  - docker

before_install:
  - docker build -t zgb0705/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zgb0705/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-udemy"
  env: "DockerUdemy-env"
  bucket_name: "elasticbeanstalk-us-west-2-844348398518"
  bucket_path: "docker-udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"